//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPeopleBotTrust
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTransaction
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string Trxn { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> TrxnType { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
